- name: Update package cache and dist-upgrade (for Debian/Ubuntu)
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist
  when: ansible_facts['pkg_mgr'] == 'apt'
  tags:
    - update
    - packages