- name: Reload unattended-upgrades
  ansible.builtin.command:
    cmd: dpkg-reconfigure -f noninteractive -plow unattended-upgrades
  register: unattended_upgrades_result
  changed_when: unattended_upgrades_result.rc != 0
  tags:
    - unattended_upgrades
    - handlers
