- name: Reload unattended-upgrades
  ansible.builtin.command:
    cmd: dpkg-reconfigure -f noninteractive -plow unattended-upgrades
  register: unattended_upgrades_result
  become: true
  changed_when: false
  tags:
    - unattended_upgrades
    - handlers
