---
- name: Disable swap
  ansible.builtin.command: swapoff -a
  when: ansible_facts['swaptotal_mb'] > 0
  changed_when: false
  become: true

- name: Disable swap entry in /etc/fstab
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+.*)$'
    replace: '# \1'
  become: true